openapi: 3.1.1
jsonSchemaDialect: https://spec.openapis.org/oas/3.1/dialect/base
info:
  title: Transparency Exchange API
  summary: The OWASP Transparency Exchange API specification for consumers and publishers
  description: TBC
  contact:
    name: TEA Working Group
    email: tbc@somewhere.tld
    url: https://github.com/CycloneDX/transparency-exchange-api
  license:
    name: Apache 2.0
    url: https://github.com/CycloneDX/transparency-exchange-api/blob/main/LICENSE
  version: 0.0.3
servers:
  - url: http://localhost/tea/v1
    description: Local development
paths:
  /product/{uuid}:
    get:
      description: Returns the corresponding TEA components for a given TEA product UUID.
      operationId: getTeaProductByUuid
      parameters:
        - name: uuid
          in: path
          required: true
          description: UUID of the TEA product in the TEA server
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Requested TEA Product found and returned
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/product"
        '400':
          $ref: "#/components/responses/400-invalid-request"
        '404':
          $ref: "#/components/responses/404-object-by-id-not-found"
      tags:
        - TEA Product
  /products:
    get:
      description: Returns a list of TEA products. Note that multiple products may
        match.
      operationId: getTeaProductByIdentifier
      parameters:
        - $ref: "#/components/parameters/page-offset"
        - $ref: "#/components/parameters/page-size"
        - $ref: "#/components/parameters/tei_urn"
      responses:
        '200':
          $ref: "#/components/responses/paginated-product"
        '400':
          $ref: "#/components/responses/400-invalid-request"
        '404':
          $ref: "#/components/responses/404-object-by-id-not-found"
      tags:
        - TEA Product
  /component/{uuid}:
    get:
      description: Get a TEA Component
      operationId: getTeaComponentById
      parameters:
        - name: uuid
          in: path
          required: true
          description: UUID of TEA Component in the TEA server
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Requested TEA Component found and returned
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/component"
        '400':
          $ref: "#/components/responses/400-invalid-request"
        '404':
          $ref: "#/components/responses/404-object-by-id-not-found"
      tags:
        - TEA Component
  /component/{uuid}/releases:
    get:
      description: Get releases of the component
      operationId: getReleasesByComponentId
      parameters:
        - name: uuid
          in: path
          required: true
          description: UUID of TEA Component in the TEA server
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Requested Releases of TEA Component found and returned
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/release"
        '400':
          $ref: "#/components/responses/400-invalid-request"
        '404':
          $ref: "#/components/responses/404-object-by-id-not-found"
      tags:
        - TEA Component
  /release/{uuid}/collection:
    get:
      description: Get the latest TEA Collection belonging to the TEA Release
      operationId: getLatestCollectionByReleaseId
      parameters:
        - name: uuid
          in: path
          required: true
          description: UUID of TEA Release in the TEA server
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Requested TEA Collection found and returned
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/collection"
        '400':
          $ref: "#/components/responses/400-invalid-request"
        '404':
          $ref: "#/components/responses/404-object-by-id-not-found"
      tags:
        - TEA Release
  /release/{uuid}/collections:
    get:
      description: Get the TEA Collections belonging to the TEA Release
      operationId: getCollectionsByReleaseId
      parameters:
        - name: uuid
          in: path
          required: true
          description: UUID of TEA Release in the TEA server
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Requested TEA Collection found and returned
          content:
            application/json:
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/collection"
        '400':
          $ref: "#/components/responses/400-invalid-request"
        '404':
          $ref: "#/components/responses/404-object-by-id-not-found"
      tags:
        - TEA Release
  /release/{uuid}/collection/{version}:
    get:
      description: Get all versions of a TEA Collection by its UUID
      operationId: getTeaCollectionVersionByCollectionIdAndVersion
      parameters:
        - name: uuid
          in: path
          required: true
          description: UUID of TEA Collection in the TEA server
          schema:
            "$ref": "#/components/schemas/uuid"
        - name: version
          in: path
          required: true
          description: Version of TEA Collection
          schema:
            type: integer
      responses:
        '200':
          description: Requested TEA Collection Version found and returned
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/collection"
        '400':
          $ref: "#/components/responses/400-invalid-request"
        '404':
          $ref: "#/components/responses/404-object-by-id-not-found"
      tags:
        - TEA Release
  /artifact/{uuid}:
    get:
      description: Get metadata for specific TEA artifact
      operationId: getArtifact
      parameters:
        - name: uuid
          in: path
          required: true
          description: UUID of TEA Artifact in the TEA server
          schema:
            "$ref": "#/components/schemas/uuid"
      responses:
        '200':
          description: Requested TEA Artifact metadata found and returned
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/artifact"
        '400':
          $ref: "#/components/responses/400-invalid-request"
        '404':
          $ref: "#/components/responses/404-object-by-id-not-found"
      tags:
        - TEA Artifact
components:
  schemas:
    #
    # Definitions reused in multiple domain objects
    #
    date-time:
      type: string
      description: Timestamp
      format: date-time
      pattern: "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}Z$"
    identifier:
      type: object
      description: An identifier with a specified type
      properties:
        idType:
          description: Type of identifier, e.g. `tei`, `purl`, `cpe`
          "$ref": "#/components/schemas/identifier-type"
        idValue:
          description: Identifier value
          type: string
    identifier-type:
      type: string
      description: Enumeration of identifiers types
      enum:
        - cpe
        - tei
        - purl
    uuid:
      type: string
      description: A UUID
      format: uuid
      pattern: "^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$"

    #
    # TEA Product
    #
    product:
      type: object
      description: A TEA product
      properties:
        uuid:
          description: A unique identifier for the TEA product
          "$ref": "#/components/schemas/uuid"
        name:
          type: string
          description: Product name
        identifiers:
          type: array
          description: List of identifiers for the product
          items:
            "$ref": "#/components/schemas/identifier"
        components:
          type: array
          description: List of TEA components for the product
          items:
            description: Unique identifier of the TEA component
            "$ref": "#/components/schemas/uuid"
      required:
        - uuid
        - name
        - identifiers
        - components
      examples:
        - uuid: 09e8c73b-ac45-4475-acac-33e6a7314e6d
          name: Apache Log4j 2
          identifiers:
            - idType: cpe
              idValue: cpe:2.3:a:apache:log4j
            - idType: purl
              idValue: pkg:maven/org.apache.logging.log4j/log4j-api
            - idType: purl
              idValue: pkg:maven/org.apache.logging.log4j/log4j-core
            - idType: purl
              idValue: pkg:maven/org.apache.logging.log4j/log4j-layout-template-json
          components:
            - 3910e0fd-aff4-48d6-b75f-8bf6b84687f0
            - b844c9bd-55d6-478c-af59-954a932b6ad3
            - d6d3f754-d4f4-4672-b096-b994b064ca2d

    #
    # TEA Component and related objects
    #
    component:
      type: object
      description: A TEA component
      properties:
        uuid:
          description: A unique identifier for the TEA component
          "$ref": "#/components/schemas/uuid"
        name:
          type: string
          description: Component name
        identifiers:
          type: array
          description: List of identifiers for the component
          items:
            "$ref": "#/components/schemas/identifier"
      required:
        - uuid
        - name
        - identifiers
        - versions
      examples:
        - uuid: 3910e0fd-aff4-48d6-b75f-8bf6b84687f0
          name: Apache Log4j API
          identifiers:
            - idType: purl
              idValue: pkg:maven/org.apache.logging.log4j/log4j-api
        - uuid: b844c9bd-55d6-478c-af59-954a932b6ad3
          name: Apache Log4j Core
          identifiers:
            - idType: cpe
              idValue: cpe:2.3:a:apache:log4j
            - idType: purl
              idValue: pkg:maven/org.apache.logging.log4j/log4j-core

    #
    # TEA Release and related objects
    #
    release:
      type: object
      properties:
        uuid:
          description: A unique identifier for the TEA Component Release
          "$ref": "#/components/schemas/uuid"
        version:
          description: Version number
          type: string
        release_date:
          description: Timestamp of the release (for sorting purposes)
          "$ref": "#/components/schemas/date-time"
        pre_release:
          type: boolean
          description: |
            A flag indicating pre-release (or beta) status.
            May be disabled after the creation of the release object, but can't be enabled after creation of an object.
        identifiers:
          type: array
          description: List of identifiers for the component
          items:
            "$ref": "#/components/schemas/identifier"
        # add lifecycle here
      required:
        - uuid
        - version
        - release_date
      examples:
        # Apache Tomcat 11.0.6
        - uuid: 605d0ecb-1057-40e4-9abf-c400b10f0345
          version: "11.0.6"
          release_date: 2025-04-01T15:43:00Z
          identifiers:
            - idType: purl
              idValue: pkg:maven/org.apache.tomcat/tomcat@11.0.6
        # Different release of Apache Tomcat
        - uuid: da89e38e-95e7-44ca-aa7d-f3b6b34c7fab
          version: "10.1.40"
          release_date: 2025-04-01T18:20:00Z
          identifiers:
            - idType: purl
              idValue: pkg:maven/org.apache.tomcat/tomcat@10.1.40
        # A pre-release of Apache Tomcat
        - uuid: 95f481df-f760-47f4-b2f2-f8b76d858450
          version: "11.0.0-M26"
          release_date: 2024-09-13T17:49:00Z
          pre_release: true
          identifiers:
            - idType: purl
              idValue: pkg:maven/org.apache.tomcat/tomcat@11.0.0-M26

    #
    # TEA Collection and related objects
    #
    collection:
      type: object
      description: A collection of security-related documents
      properties:
        uuid:
          "$ref": "#/components/schemas/uuid"
          description: Must match the UUID of the corresponding `release` object
        version:
          type: integer
          description: Collection version, incremented each time its content changes.
        release_date:
          "$ref": "#/components/schemas/date-time"
        update_reason:
          "$ref": "#/components/schemas/collection-update-reason"
        artifacts:
          type: array
          items:
            "$ref": "#/components/schemas/artifact"
    collection-update-reason:
      type: object
      description: Reason for the update to the TEA collection
      properties:
        type:
          "$ref": "#/components/schemas/collection-update-reason-type"
        comment:
          type: string
          description: Free text description
    collection-update-reason-type:
      type: string
      description: Type of TEA collection update
      enum:
        - INITIAL_RELEASE
        - VEX_UPDATED
        - ARTIFACT_UPDATED
        - ARTIFACT_ADDED
        - ARTIFACT_REMOVED

    #
    # TEA Artifact and related objects
    #
    artifact:
      type: object
      description: A security-related document
      properties:
        uuid:
          "$ref": "#/components/schemas/uuid"
        name:
          type: string
          description: Artifact name
        author:
          "$ref": "#/components/schemas/artifact-author"
        type:
          "$ref": "#/components/schemas/artifact-type"
        formats:
          type: array
          items:
            "$ref": "#/components/schemas/artifact-format"
    artifact-author:
      type: object
      description: The author of a document.
      properties:
        name:
          type: string
          description: The name of the author
        email:
          type: string
          description: The e-mail address of the author
          format: email
        organization:
          type: string
          description: Organization
    artifact-type:
      type: string
      description: Specifies the type of external reference.
      enum:
        - vcs
        - issue-tracker
        - website
        - advisories
        - bom
        - mailing-list
        - social
        - chat
        - documentation
        - support
        - source-distribution
        - distribution
        - distribution-intake
        - license
        - build-meta
        - build-system
        - release-notes
        - security-contact
        - model-card
        - log
        - configuration
        - evidence
        - formulation
        - attestation
        - threat-model
        - adversary-model
        - risk-assessment
        - vulnerability-assertion
        - exploitability-statement
        - pentest-report
        - static-analysis-report
        - dynamic-analysis-report
        - runtime-analysis-report
        - component-analysis-report
        - maturity-report
        - certification-report
        - codified-infrastructure
        - quality-metrics
        - poam
        - electronic-signature
        - digital-signature
        - rfc-9116
        - other
    artifact-format:
      type: object
      description: A security-related document in a specific format
      properties:
        mimeType:
          type: string
          description: The MIME type of the document
        description:
          type: string
          description: A free text describing the artifact
        url:
          type: string
          description: A download URL for the artifact
          format: url
        signature_url:
          type: string
          description: A download URL for an external signature of the artifact
          format: url
        checksums:
          type: array
          description: List of checksums for the artifact
          items:
            "$ref": "#/components/schemas/artifact-checksum"
    artifact-checksum:
      type: object
      properties:
        algType:
          "$ref": "#/components/schemas/artifact-checksum-type"
        algValue:
          type: string
          description: Checksum value
    artifact-checksum-type:
      type: string
      description: Checksum algorithm
      enum:
        - MD5
        - SHA-1
        - SHA-256
        - SHA-384
        - SHA-512
        - SHA3-256
        - SHA3-384
        - SHA3-512
        - BLAKE2b-256
        - BLAKE2b-384
        - BLAKE2b-512
        - BLAKE3
    #
    # Types used in API responses
    #
    pagination-details:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
          example: '2024-03-20T15:30:00Z'
        page_start_index:
          type: number
          format: int64
          default: 0
        page_size:
          type: number
          format: int64
          default: 100
        total_results:
          type: number
          format: int64
      required:
        - timestamp
        - page_start_index
        - page_size
        - total_results
  responses:
    204-common-delete:
      description: Object deleted successfully
      content:
        application/json: {}
    400-invalid-request:
      description: Request was Invalid
      content:
        application/json: {}
    401-unauthorized:
      description: Authentication required
      content:
        application/json: {}
    404-object-by-id-not-found:
      description: Object requested by identifier not found
      content:
        application/json: {}
    paginated-product:
      description: A paginated response containing TEA Products
      content:
        application/json:
          schema:
            allOf:
              - $ref: "#/components/schemas/pagination-details"
              - type: object
                properties:
                  results:
                    type: array
                    items:
                      "$ref": "#/components/schemas/product"
  parameters:
    # Pagination
    page-offset:
      name: page-offset
      description: Pagination offset
      in: query
      required: false
      schema:
        type: number
        format: int64
        default: 0
    page-size:
      name: page-size
      description: Pagination offset
      in: query
      required: false
      schema:
        type: number
        format: int64
        default: 100
    # Identifiers
    tei_urn:
      name: tei_urn
      description: Transparency Exchange Identifier (URN)
      in: query
      required: true
      schema:
        type: string
        pattern: '^urn:tei:[a-z]+:[a-zA-Z0-9.-]+:[a-zA-Z0-9-]+$'
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    basicAuth:
      type: http
      scheme: basic
security:
  - bearerAuth: []
  - basicAuth: []
tags:
  - name: TEA Product
  - name: TEA Component
  - name: TEA Release
  - name: TEA Artifact
externalDocs:
  description: Transparency Exchange API specification
  url: https://github.com/CycloneDX/transparency-exchange-api
